services:
    app_tracker:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app_tracker
        volumes:
            - classifer:/app/classifer
        restart: always
        depends_on:
            - mongodb

    ollama:
        image: ollama/ollama:latest
        container_name: ollama
        restart: always
        ports:
            - "11434:11434"

    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - data:/data/db

volumes:
    data:
        driver: local
    classifer:
        driver: local
