services:
    app_tracker:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app_tracker
        environment:
            - MONGO_URI=mongodb://mongodb:27017
            - OLLAMA_HOST=http://ollama:11434
            - EMAIL_HOST=your_email_host
            - EMAIL_HOST_USER=your_email_user
            - EMAIL_HOST_PASSWORD=your_email_password
            - DISCORD_TOKEN=your_discord_token
            - DISCORD_USER_ID=your_discord_user_id
        volumes:
            - models:/usr/src/app/models
        restart: always
        depends_on:
            - mongodb

    ollama:
        image: ollama/ollama:latest
        container_name: ollama
        restart: always
        ports:
            - "11434:11434"

    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - data:/data/db

volumes:
    data:
        driver: local
    models:
        driver: local
